### PR TITLE
Bug issue of footer

### PR DESCRIPTION
**Pull request by xiaoshaotongzhi**

### CODE REVIEW

**Review by MeiH10 — CHANGES_REQUESTED** [review]
Why are you getting rid of HomeCSS? You shouldn't have to change that. Just use tailwind

**Comment by MeiH10** [comment]
I think I'll take a look at it.

**Comment by xiaoshaotongzhi** [comment]
I have solved this comments by only using tailwind now.

**Comment by xiaoshaotongzhi** [comment]
> I think I'll take a look at it.

I have solved this problem by only using tailwind. Please check it.

**Comment by MeiH10** [comment]
like I said, this gets rid of the margin i want on the carousel. don't worry about it, i'll look into this myself

**Pull request closed without merging**
