### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by jiec137**

### CODE REVIEW

**Comment by MeiH10** [comment]
@jiec137 it looks like you used some new dependencies, but you didn't add them to package.json. As a result, I can't simply npm i them. Please add the dependencies you used to package.json.

**Comment by jiec137** [comment]
> @jiec137 it looks like you used some new dependencies, but you didn't add them to package.json. As a result, I can't simply npm i them. Please add the dependencies you used to package.json.

I've updated the package.json, however i just noticed create event modal isn't working correctly in dark mode, working on a fix now.

**Comment by MeiH10** [comment]
yeah it looks like all the modal(forms) seems a bit off. Also would it be possible to have dark mode off as a default? Right now, it's dark mode is on by default. We can work on designing the specific color scheme we want for dark mode next week, but it looks good so far.

**Comment by jiec137** [comment]
> yeah it looks like all the modal(forms) seems a bit off(could be due to some fonts having same/similar color to the background). Also would it be possible to have dark mode off as a default? Right now, it's dark mode is on by default. We can work on designing the specific color scheme we want for dark mode next week, but it looks good so far.

I've made it so that light theme is on default and "remembers" user's preference based on their last chosen theme. For the forms, do you think I should integrate dark mode into forms or just fix the font color so that it doesn't change when it's dark mode.

**Comment by MeiH10** [comment]
I think it might be better to integrate dark mode into forms. But you can try out both method and take a screenshot of how they look.

**Comment by jiec137** [comment]
Hi Mei, I've fixed the forms and the home page text. There is one more thing I need to fix is that the website automatically reset to light theme when the page is refreshed, and I can't find a way to fix that. Can you take a look on that?

**Comment by jiec137** [comment]
> > Hi Mei, I've fixed the forms and the home page text. There is one more thing I need to fix is that the website automatically reset to light theme when the page is refreshed, and I can't find a way to fix that. Can you take a look on that?
> 
> Yeah we can definitely take a look at that tmr. It might have something to do with colorScheme not being stored correctly or fetched correctly from localstorage.
> 
> One more thing, I noticed when the site first loads(fresh, brand new tab), the toggle is at dark mode, but the page is in light mode. I had to click on the toggle twice to reset it to normal. image

Yes it was the colorScheme issue, turns out I accidentally deleted useColorScheme when I was editing ThemeContext. I've fixed it, the toggle and page refreshing should work now.

**Comment by MeiH10** [comment]
Great job! I think we still need to fix a few font color(like the `I accept the `, the `sort by`, `order`, all the tags. But these should be easy.

**Review by MeiH10 — APPROVED** [review]
Awesome!

**Pull request merged**
